apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: CELERY_BROKER_URL
              value: amqp://guest:guest@rabbitmq//
            - name: CELERY_RESULT_BACKEND
              value: redis://redis:6379/0
            - name: POSTGRES_HOST
              value: db
            - name: REDIS_HOST
              value: redis
          image: chanawh/web:latest
          imagePullPolicy: Never
          name: web-app
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: web-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: web-cm0
          name: web-cm0
